In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
B = A.copy()
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
From = 2.5
To = 7  # не включительно
Step = 0.5
A = np.arange(From, To, Step)
A

array([2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [8]:
A = np.full((5, 6), 4.5)
A

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [10]:
B = np.empty((5, 6)) # пустой массив указанной формы (данными из текущего участка памяти)
B

array([[4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5, 4.5, 4.5, 4.5]])

In [13]:
# Создание единичнодиагонального массива
C = np.identity(4)  #размерность матрицы
C

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# Создание нулевого/единичного массива с заданными размерами
A = np.zeros((2, 3, 2))
B = np.ones((3, 2))
C = np.eye(5)

A

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [4]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Векторные операции

In [6]:
A = [1, 2, 3, 4,]  # список, при сложенеии произойдет конкатенация
B = [5, 6, 7, 8, 9]
A + B

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
A = np.array([[-1, 2, 3], [4, 5, 6], [7, 8, 9]])  # числовые векторы, а не массивы данных
B = np.array([[1, -2, -3], [7, 8, 9], [4, 5, 6]])

A + B

array([[ 0,  0,  0],
       [11, 13, 15],
       [11, 13, 15]])

In [8]:
A - B

array([[-2,  4,  6],
       [-3, -3, -3],
       [ 3,  3,  4]])

In [18]:
#Все арифметическеи операции и возведение в степень
A = np.ones((3,3))
B = np.full_like(A, 4)  #like-функция - размерность А значениями 4

In [19]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
B 

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [22]:
A * B

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [23]:
A / B

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

In [24]:
A ** B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
B ** A

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [35]:
#То же, если один из аргументов - константа
A = np.array([[-1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = -2.
A

array([[-1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [28]:
A + B

array([[-3,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [29]:
A - B

array([[ 1,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
A * B

array([[  2,  -4,  -6],
       [ -8, -10, -12],
       [-14, -16, -18]])

In [31]:
A / B

array([[ 0.5, -1. , -1.5],
       [-2. , -2.5, -3. ],
       [-3.5, -4. , -4.5]])

In [36]:
A ** B

array([[1.        , 0.25      , 0.11111111],
       [0.0625    , 0.04      , 0.02777778],
       [0.02040816, 0.015625  , 0.01234568]])

In [37]:
B ** A

array([[-5.00e-01,  4.00e+00, -8.00e+00],
       [ 1.60e+01, -3.20e+01,  6.40e+01],
       [-1.28e+02,  2.56e+02, -5.12e+02]])

In [39]:
# broadcast - если аргументы A и B - массивы разных размерностей
A = np.ones((3,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
B = np.arange(4)
B 

array([0, 1, 2, 3])

In [41]:
A + B

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [42]:
A - B

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [43]:
A * B

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [44]:
A / B

C:\Users\esgre\AppData\Local\Temp\ipykernel_9948\3006334257.py:1: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 1.        , 0.5       , 0.33333333]])

In [45]:
np.isinf(A/B)  # проверка на наличие в массиве занчения infinity

C:\Users\esgre\AppData\Local\Temp\ipykernel_9948\2361930089.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.isinf(A/B)  # проверка на наличие в массиве занчения infinity


array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [46]:
np.isinf(A/B).any()

C:\Users\esgre\AppData\Local\Temp\ipykernel_9948\3223077836.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.isinf(A/B).any()


True

In [47]:
# если не получается совместить размерности A и B?
A = np.ones((3, 3))
B = np.zeros((2, 4))

In [48]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
A * B  # broadcast вернёт ошибку ValueError: operands could not be broadcast together with shapes (3,3) (2,4)

ValueError: operands could not be broadcast together with shapes (3,3) (2,4) 

# Работа с массивами как с элементами векторного пространства

In [9]:
from numpy import linalg as linalg

In [4]:
# операции над матрицами: произведение и воззведениев степень

A = np.ones((4, 3))
B = np.full((3, 5), 3)

In [5]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
B 

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [7]:
# два способа перемножения: np.matmul() и np.dot()
np.matmul(A, B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [8]:
np.dot(A, B)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [11]:
# возведение в степень 
A = np.ones((3, 3))
linalg.matrix_power(A, 2)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [13]:
linalg.matrix_power(A, 3)

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

Характеристика матриц и векторов:
- норма
- айгенпары
- определители

In [14]:
A = np.ones(5)
A

array([1., 1., 1., 1., 1.])

In [16]:
linalg.norm(A)  # норма матрицы

2.23606797749979

In [17]:
np.sqrt(5)

2.23606797749979

Собственные числа и собственные векторы

In [19]:
A = np.array([[-1, -6], [2, 6]])
A

array([[-1, -6],
       [ 2,  6]])

In [20]:
linalg.eig(A)

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

Решение систем линейных уравнений вида Ax = b в numpy

In [21]:
A = np.array([[1, 2], [3, 1]])
b = np.array([5, 0])

In [22]:
A

array([[1, 2],
       [3, 1]])

In [23]:
b

array([5, 0])

In [24]:
linalg.solve(A, b)

array([-1.,  3.])

Вычисление определителя матрицы

In [25]:
A = np.array([[1, 3], [2, 6]])
A

array([[1, 3],
       [2, 6]])

In [27]:
linalg.det(A)

0.0

In [28]:
A = np.array([[4, 3], [2, 6]])
A
linalg.det(A)

17.999999999999996