# Индексация массивов. Срезы. Типы данных

In [2]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Индексация массивов происходит как индексация списков, но с особенностями

In [3]:
A[0]

array([1, 2, 3])

In [4]:
A[1]

array([4, 5, 6])

In [5]:
A[2]

array([7, 8, 9])

In [6]:
# каждый новый индекс уменьшает размерность возвращаемого значения
A[0][0]

1

In [7]:
# если нужно выбрать столбец, второй индекс один и тот же
A[:,0] # первый индекс ":" - все элементы этой оси

array([1, 4, 7])

In [8]:
A[:,1]

array([2, 5, 8])

In [10]:
A[:,2]

array([3, 6, 9])

# Изменение формы массива

In [11]:
# Форма массива - это набор чисел, определяющий количество элементов вдоль каждой из осей

A.shape

(3, 3)

In [13]:
B = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
B 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
B.shape

(2, 5)

In [15]:
# изменить форму массива - перераспределить его элементы в другом порядке вдооль других осей
# .reshape()
A = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
A.shape

(2, 6)

In [17]:
A_reshaped = A.reshape(6, 2)
A_reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [18]:
A_reshaped.shape

(6, 2)

In [19]:
A2_reshaped = A.reshape(12, 1)
A2_reshaped

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [20]:
A2_reshaped.shape

(12, 1)

In [21]:
# изменить размер массива, если известно лишь одно измерение целевого массива
# 2*6 = 12, она сторона - 2, другая - 3, третья - 12/(2*3) = 2

A3_reshaped = A.reshape(2, 3, 2)
A3_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [22]:
A3_reshaped.shape

(2, 3, 2)

In [23]:
# не считать третий (-1)

A4_reshaped = A.reshape(2, 3, -1)
A4_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [24]:
A4_reshaped.shape

(2, 3, 2)

In [25]:
# не считать любую сторону

A5_reshaped = A.reshape(2, -1, 2)
A5_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [26]:
A5_reshaped.shape

(2, 3, 2)

In [27]:
# неверный ppfghjc reshape

A.reshape(12, -1, 2)

ValueError: cannot reshape array of size 12 into shape (12,newaxis,2)

# Транспонирование

In [28]:
A = np.zeros((1, 2, 3, 4, 5, 6))
A.shape

(1, 2, 3, 4, 5, 6)

In [30]:
# Транспонирование - изменение порядка следования осей

A_transposed = A.T
A_transposed.shape

(6, 5, 4, 3, 2, 1)

In [31]:
A1_transposed = np.transpose(A)
A1_transposed.shape

(6, 5, 4, 3, 2, 1)

In [33]:
A2_transposed = np.transpose(A, (0, 1, 3, 2, 4, 5))  # замена осей 2 и 3 местами
A2_transposed.shape

(1, 2, 4, 3, 5, 6)

# Соединение массивов

In [47]:
# Конкатенация - объединение нескольких массивов в один в случае сохранения количества осей

A = np.zeros((5, 6))
B = np.ones((5, 6))

In [35]:
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
B

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [38]:
B = np.ones_like(A)
B 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
np.concatenate((A, B), axis = 0)  # конкатенация по оси строк

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.concatenate((A, B), axis = 1)  # конкатенация по оси столбцов

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.concatenate((A, B), axis = -1)

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [43]:
A = np.zeros((5, 6))
B = np.ones((2, 6))  # другая размерность по строкам

In [44]:
np.concatenate((A, B), axis = 0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [45]:
np.concatenate((A, B), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 2

In [48]:
# соединить массивы по третьей пока не существующей оси
# нужны одинаоквы массивы

np.stack((A, B), axis = 0)

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [49]:
np.stack((A, B), axis = 0).shape

(2, 5, 6)

In [50]:
np.stack((A, B), axis = 1)

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.]]])

In [51]:
np.stack((A, B), axis = 1).shape

(5, 2, 6)

# Срезы 

In [52]:
A = np.arange(0, 60).reshape(6, 10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [53]:
A[2:5]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
A[2:5:2]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
A[::2]  # start и stop по default, step = 2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
A[::-1]  # в обратном порядке

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [57]:
A[2:5, 2:7]  # 2:5 по строкам, 2:7 - по столбцам

array([[22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

In [ ]:
import matplotlib.pyplot as plt
image = plt.imread("example.jpg")
plt.figure(figsize = (15, 13))
plt.imshow(image)

In [ ]:
image.shape

In [ ]:
# .T здесь не поддходит, пиксели должны идти в конце

image_transposed = np.transpose(image, (1, 0, 2))

In [ ]:
plt.figure(figsize = (15, 13))
plt.imshow(image_transposed)

In [ ]:
# инверсия цвета как срез массива

plt.figure(figsize = (15, 13))
plt.imshow(image[:, :, ::-1])  # первые две размерности не трогаются, развоот по третьей размерности

In [ ]:
# разреживание изображения

plt.figure(figsize = (15, 13))
plt.imshow(image[::2, ::4])

In [ ]:
# выделить куски изображения при помощи срезов

part_of_image = image[:600, :800, :]
plt.figure(figsize = (15, 13))
plt.imshow(part_of_image)

In [ ]:
part_of_image = image[600:, 800:, :]
plt.figure(figsize = (15, 13))
plt.imshow(part_of_image)

# Другие операции с массивами

In [60]:
# фильтрация массива при помощи индексирующего массива

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

newarr = arr[x]
print(newarr)

[41 43]


In [61]:
# отфильтровать элементы массива по определённому условию

index_array = [ True if x > 42 else False for x in arr]
index_array

[False, False, True, True]

In [62]:
arr[index_array]

array([43, 44])

In [63]:
index_array

[False, False, True, True]

In [64]:
# проще

index_array = arr > 42
arr[index_array]

array([43, 44])

In [65]:
arr[arr > 42]

array([43, 44])

In [66]:
# поиск по определённому условию в массиве

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

x

(array([3, 5, 6], dtype=int32),)

In [67]:
arr[x]

array([4, 4, 4])

In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)

x

(array([0, 2, 4, 6], dtype=int32),)

In [69]:
arr[x]

array([1, 3, 5, 7])

In [70]:
# поиск в отсортированном массиве

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)

x

1

In [71]:
# отсортировать массив

np.sort(arr)

array([6, 7, 8, 9])

In [73]:
# сортировка по определённой оси

arr = np.arange(20, 0, -1).reshape(5, 4)
arr

array([[20, 19, 18, 17],
       [16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [74]:
np.sort(arr) # просто сортировка, по строчкам

array([[17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [75]:
np.sort(arr, axis = 0) # сортировка по столбцам

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13],
       [20, 19, 18, 17]])

In [76]:
np.sort(np.sort(arr, axis = 1), axis = 0)  # полная сортировка 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])